In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## First issue is that 10X and MOp cluster_label celltypes are not explicitly matched

I have ontologies like L5 IT Tcap_2 for 10X, but L5_IT_1 from MERFISH

In [4]:
rzs_meta = pd.read_csv('../../../readzs_fork/MOp_10Xv3_metadata.tsv',sep='\t')
rzs_meta.head()

,cell_id,cluster_id,library,cell_bc,cluster_label,subclass_label,class_label,cluster_color,size
0,L8TX_181211_01_G12_AAACCCAAGCTTCATG,42,L8TX_181211_01_G12,AAACCCAAGCTTCATG,L5 IT Tcap_2,L5 IT,Glutamatergic,#52CA74,17334
1,L8TX_181211_01_G12_AAACCCACACCAGCCA,42,L8TX_181211_01_G12,AAACCCACACCAGCCA,L5 IT Tcap_2,L5 IT,Glutamatergic,#52CA74,17334
2,L8TX_181211_01_G12_AAACGAACAACGATTC,42,L8TX_181211_01_G12,AAACGAACAACGATTC,L5 IT Tcap_2,L5 IT,Glutamatergic,#52CA74,17334
3,L8TX_181211_01_G12_AAACGAATCTCGTGAA,42,L8TX_181211_01_G12,AAACGAATCTCGTGAA,L5 IT Tcap_2,L5 IT,Glutamatergic,#52CA74,17334
4,L8TX_181211_01_G12_AAACGCTGTAGTCACT,42,L8TX_181211_01_G12,AAACGCTGTAGTCACT,L5 IT Tcap_2,L5 IT,Glutamatergic,#52CA74,17334

In [7]:
rzs_meta['cluster_label'].nunique()

78

In [5]:
rzs_meta['cluster_label'].unique()

array(['L5 IT Tcap_2', 'L5 IT Tcap_1', 'Vip Gpc3', 'Vip Htr1f_2',
       'L6 IT Sulf1_4', 'Vip C1ql1', 'L6 CT Nxph2 Kit', 'L2/3 IT',
       'Oligo Opalin_1', 'L6 CT Cpa6_2', 'L5 IT S100b', 'L5 IT Pld5',
       'L6 CT Cpa6_1', 'Sst Crhr2_1', 'Lamp5 Slc35d3_1', 'Vip Cbln4_2',
       'L6 IT Sulf1_3', 'L6 NP Trh_1', 'Vip Chat', 'L5 NP Slc17a8_2',
       'Vip Mybpc1_1', 'Sst Hpse_2', 'L6 IT Sulf1_1', 'L5 NP Slc17a8_1',
       'Macrophage', 'Vip Serpinf1', 'Sst Myh8_2', 'L6 NP Trh_3',
       'Lamp5 Egln3_2_1', 'Sst Myh8_1', 'Vip Crispld2', 'Astro Aqp4',
       'OPC Pdgfra', 'L6 IT Sulf1_2', 'L6b Rprm', 'L6 CT Nxph2 Pou3f2_2',
       'Lamp5 Pax6', 'Vip Igfbp6', 'Lamp5 Pdlim5_2', 'VLMC Kcnj8',
       'Lamp5 Pdlim5_1', 'L6 CT Gpr139', 'Vip Lypd1', 'Sst Calb2',
       'Sst Pvalb Etv1', 'Endo Slc38a5_1', 'Sst C1ql3_1',
       'L5 NP Slc17a8_3', 'Vip Col14a1', 'L5 ET_2', 'Sst Hpse_3',
       'L6 IT Car3', 'SMC', 'Sncg_2', 'Vip Cbln4_1', 'L6b Shisa6',
       'Vip Mybpc1_2', 'Lamp5 Lhx6', 'Sst Crhr2_2',
       'L6 CT Nxph2 Pou3f2_1', 'L5 ET_3', 'Oligo Enpp6_2', 'Sst Hspe_1',
       'Sst C1ql3_2', 'Vip Htr1f_1', 'L5 ET_1', 'Oligo Opalin_2',
       'Sncg_1', 'L6b Ror1', 'Sst Th', 'L6 NP Trh_2', 'Oligo Enpp6_1',
       'Sst Chodl', 'Pvalb Reln', 'Pvalb Gabrg1', 'L6b Kcnip1',
       'Pvalb Calb1', 'Pvalb Vipr2'], dtype=object)

In [8]:
mop_meta = pd.read_csv(
    '/oak/stanford/groups/horence/rob/isoform_localizations/unprocessed_downloads/dl_scripts/revised_collection/cell_labels.csv',
)
display(mop_meta.head())
display(mop_meta['label'].nunique())
mop_meta['label'].unique()

,Unnamed: 0,sample_id,slice_id,class_label,subclass,label
0,10000143038275111136124942858811168393,mouse2_sample4,mouse2_slice31,Other,Astro,Astro_1
1,100001798412490480358118871918100400402,mouse2_sample5,mouse2_slice160,Other,Endo,Endo
2,100006878605830627922364612565348097824,mouse2_sample6,mouse2_slice109,Other,SMC,SMC
3,100007228202835962319771548915451072492,mouse1_sample2,mouse1_slice71,Other,Endo,Endo
4,100009332472089331948140672873134747603,mouse2_sample5,mouse2_slice219,Glutamatergic,L2/3 IT,L23_IT_3

99

array(['Astro_1', 'Endo', 'SMC', 'L23_IT_3', 'VLMC', 'L6_CT_5',
       'L45_IT_2', 'L45_IT_SSp_2', 'Peri', 'L5_ET_1', 'L45_IT_1',
       'L45_IT_5', 'L45_IT_3', 'L23_IT_4', 'L5_IT_1', 'Micro_1',
       'L23_IT_2', 'L5_ET_5', 'Sst_3', 'L6_IT_3', 'Oligo_1', 'L5_ET_4',
       'Sncg_1', 'L6_IT_Car3', 'Vip_7', 'PVM', 'L5_ET_3', 'L56_NP_1',
       'Pvalb_6', 'L6_CT_3', 'L5_IT_2', 'L6_CT_1', 'L45_IT_SSp_1',
       'Astro_2', 'Pvalb_5', 'L56_NP_2', 'Oligo_2', 'L6_IT_1', 'L6_CT_2',
       'Pvalb_3', 'OPC', 'striatum_1', 'L5_IT_3', 'L23_IT_1', 'Oligo_3',
       'Pvalb_4', 'Vip_1', 'L23_IT_5', 'L6_CT_6', 'Pvalb_1', 'Pvalb_7',
       'L5_IT_4', 'L6b_2', 'L6_CT_4', 'Vip_3', 'Vip_10', 'striatum_2',
       'Sst_2', 'L6_IT_2', 'L6b_1', 'L6_CT_8', 'Pvalb_10', 'L5_ET_2',
       'L6_CT_7', 'Micro_2', 'L45_IT_4', 'Sst_1', 'Pvalb_2', 'Vip_6',
       'Lamp5_1', 'L6b_3', 'ventricle_1', 'Lamp5_5', 'Sncg_2', 'Sst_6',
       'Vip_8', 'Sst_5', 'Sst_4', 'Astro_3', 'Vip_2', 'Pvalb_8',
       'Lamp5_9', 'Lamp5_3', 'Vip_4', 'Lamp5_8', 'Sst_7', 'Sst_8',
       'L6_CT_9', 'Lamp5_4', 'Pvalb_9', 'Pvalb_11', 'Lamp5_6', 'Lamp5_2',
       'Sst_Chodl', 'Vip_9', 'Lamp5_7', 'Vip_5', 'ventricle_2',
       'Pvalb_12'], dtype=object)

# Attempting to get comparable labels from Pachter's paper

They did clustering etc to get their own labels to be able to compare between MERFISH and 10X and SS2

I cloned their repo here: https://github.com/pachterlab/BYVSTZP_2020/tree/master/reference but I didn't find any mapping from MERFISH cell-type to 10X or SS2 cell-type

I also checked the supplemental tables, and the info is not there either

Re-reading the paper and looking through the analysis jupyter notebooks in the github repo, they didn't do any analysis on the "cluster-label" level for the MERFISH data, everything is at the "subclass_label" which is what I'm currently doing

In [9]:
#MERFISH cell-labels table has a row for each cell
#with label column (nearly directly from MERFISH metadata)
#and label_v1 which are new labels from the Pacther analysis
merf_cell_labels = pd.read_csv('/oak/stanford/groups/horence/rob/isoform_localizations/SRRS/pachter_annotations/BYVSTZP_2020/reference/merfish/cell_labels.csv')
merf_cell_labels.head()

,Unnamed: 0,label,subclass,sampleID,sliceID,label_v1,AP_distance (um),pos_x (um),pos_y (um)
0,00002e16-356f-419f-b96e-ec7a9327033d,Sst_1,Sst,dataset2_sample6,dataset2_slice109,I30,1180,-79.474594,2211.467867
1,000068a9-c788-4aa6-becc-175159da9f44,Endo,Endothelial,dataset1_sample1,dataset1_slice50,Endo,490,3837.284502,-3847.753461
2,0000691f-e1ef-43a9-90c4-82f1ea0c3fde,L6_IT_1,L6_IT,dataset2_sample3,dataset2_slice139,E8,1480,3502.243851,-3511.940334
3,00008097-f502-40d1-a486-c61cdd999e7d,L2/3_IT_3,L2/3_IT,dataset2_sample1,dataset2_slice61,E2,700,-3975.718063,-2609.660891
4,0000892d-7e0b-4ff4-b445-7ceb69ac8cfb,VLMC,VLMC,dataset1_sample5,dataset1_slice260,VLMC,2590,-6370.114257,623.408623

In [17]:
merf_labels = set(mop_meta['label'])
pachter_merf_labels = set(merf_cell_labels['label'])

print(len(merf_labels))
print(len(pachter_merf_labels))
print(len(merf_labels.intersection(pachter_merf_labels)))

99
93
62

In [22]:
merf_cell_labels['label_v1'].unique()

array(['I30', 'Endo', 'E8', 'E2', 'VLMC', 'I32', 'E1', 'E25', 'E9', 'E17',
       'E7', 'I20', 'I39', 'E16', 'E22', 'Oligo', 'I29', 'E26', 'Micro',
       'E27', 'E3', 'E11', 'E5', 'E13', 'Peri', 'Astro', 'E0', 'I6',
       'E29', 'E4', 'E10', 'E24', 'E23', 'E18', 'OPC', 'I3', 'E36', 'E41',
       '-1', 'E6', 'I27', 'SMC', 'E37', 'I8', 'E12', 'I26', 'I35', 'I2',
       'other', 'E31', 'E14', 'E34', 'E35', 'I33', 'E30', 'I44', 'Macro',
       'E39', 'I38', 'I15', 'E15', 'I31', 'I14', 'E28', 'I18', 'E33',
       'I17', 'I1', 'I21', 'I28', 'I34', 'I16', 'I0', 'I47', 'I4', 'I12',
       'E32', 'I13', 'I37', 'I41', 'E42', 'I49', 'I50', 'I23', 'Epen'],
      dtype=object)

In [28]:
# MERFISH cell_metadata.csv I think is straight from the Zhuang paper without changes
merf_cell_meta = pd.read_csv('/oak/stanford/groups/horence/rob/isoform_localizations/SRRS/pachter_annotations/BYVSTZP_2020/reference/merfish/cell_metadata.csv')
merf_cell_meta.head()

,Unnamed: 0,fovID,fov_x,fov_y,volume,center_x,center_y,slice_id,sample_id,label,subclass,class_label
0,1.000010e+37,13,4539.310,2986.899,992.830060,4738.397298,3075.327399,mouse2_slice31,dataset2_sample4,Astro_1,Astrocytes,Other
1,1.000020e+38,290,-4016.860,1404.780,610.091871,-3964.711404,1451.889047,mouse2_slice160,dataset2_sample5,Endo,Endothelial,Other
2,1.000070e+38,113,750.406,1143.102,148.277718,805.843523,1215.035473,mouse2_slice109,dataset2_sample6,SMC,SMC,Other
3,1.000070e+38,432,1262.680,-3752.030,249.515471,1348.686198,-3589.955255,mouse1_slice71,dataset1_sample2,Endo,Endothelial,Other
4,1.000090e+38,354,-3627.450,-1987.730,1779.831996,-3584.650904,-1883.105955,mouse2_slice219,dataset2_sample5,L23_IT_3,L23_IT,Glutamatergic

In [30]:
#10Xv3 cluster.annotation.csv does not have the "label_v1" column I'm looking for
tenX_meta = pd.read_csv('/oak/stanford/groups/horence/rob/isoform_localizations/SRRS/pachter_annotations/BYVSTZP_2020/reference/10xv3/cluster.annotation.csv')
tenX_meta

,cluster_id,cluster_label,subclass_label,class_label,cluster_color,size
0,1,Lamp5 Pax6,Lamp5,GABAergic,#DDACC9,81
1,2,Lamp5 Egln3_2_1,Lamp5,GABAergic,#DD8091,179
2,3,Lamp5 Pdlim5_1,Lamp5,GABAergic,#FF829E,247
3,4,Lamp5 Pdlim5_2,Lamp5,GABAergic,#FF7290,537
4,5,Lamp5 Slc35d3_1,Lamp5,GABAergic,#FFA388,1275
...,...,...,...,...,...,...
142,143,L6b Shisa6_low_1,Low Quality,Low Quality,#5A7A65,84
143,144,L6b Shisa6_low_2,Low Quality,Low Quality,#1F7C70,95
144,145,Oligo Opalin_neuon,doublet,Low Quality,#41775C,16
145,146,Endo Slc38a5_5,doublet,Low Quality,#4C6863,36
146,147,Endo_VLMC,doublet,Low Quality,#5A6E5E,18

In [31]:
#10Xv3 sample_metadata does not have the "label_v1" column I'm looking for either
tenX_sample_meta = pd.read_csv('/oak/stanford/groups/horence/rob/isoform_localizations/SRRS/pachter_annotations/BYVSTZP_2020/reference/10xv3/sample_metadata.csv')
tenX_sample_meta.head()

,Unnamed: 0,aggr_num,umi.counts,gene.counts,library_id,tube_barcode,Seq_batch,Region,Lib_type,Gender,...,Live_percent,Total_Cells,Live_Cells,method,exp_component_name,mapped_reads,unmapped_reads,nonconf_mapped_reads,total.reads,doublet.score
0,AAACCCAAGCTTCATG-1L8TX_181211_01_G12,1,55812,7122,L8TX_181211_01_G12,SM-HH8FP-1,RTX-841,MOp,Cells_FACS-tdT,Male,...,75%,7882,5898,10xv3,AAACCCAAGCTTCATG-1L8TX_181211_01_G12,141238,2460,11355,155053.0,0.154639
1,AAACCCAAGGCGCTTC-1L8TX_181211_01_G12,1,1670,668,L8TX_181211_01_G12,SM-HH8FP-1,RTX-841,MOp,Cells_FACS-tdT,Male,...,75%,7882,5898,10xv3,AAACCCAAGGCGCTTC-1L8TX_181211_01_G12,4160,64,1049,5273.0,0.030928
2,AAACCCAAGGCTTAAA-1L8TX_181211_01_G12,1,1873,406,L8TX_181211_01_G12,SM-HH8FP-1,RTX-841,MOp,Cells_FACS-tdT,Male,...,75%,7882,5898,10xv3,AAACCCAAGGCTTAAA-1L8TX_181211_01_G12,6404,47,2539,8990.0,0.000000
3,AAACCCAAGTGAGGTC-1L8TX_181211_01_G12,1,36622,6125,L8TX_181211_01_G12,SM-HH8FP-1,RTX-841,MOp,Cells_FACS-tdT,Male,...,75%,7882,5898,10xv3,AAACCCAAGTGAGGTC-1L8TX_181211_01_G12,90968,1351,7997,100316.0,0.163265
4,AAACCCACACCAGCCA-1L8TX_181211_01_G12,1,90475,8322,L8TX_181211_01_G12,SM-HH8FP-1,RTX-841,MOp,Cells_FACS-tdT,Male,...,75%,7882,5898,10xv3,AAACCCACACCAGCCA-1L8TX_181211_01_G12,240181,4107,20590,264878.0,0.164948

In [32]:
tenX_sample_meta.columns

Index(['Unnamed: 0', 'aggr_num', 'umi.counts', 'gene.counts', 'library_id',
       'tube_barcode', 'Seq_batch', 'Region', 'Lib_type', 'Gender', 'Donor',
       'Amp_Name', 'Amp_Date', 'Amp_PCR_cyles', 'Lib_Name', 'Lib_Date',
       'Replicate_Lib', 'Lib_PCR_cycles', 'Lib_PassFail', 'Cell_Capture',
       'Lib_Cells', 'Mean_Reads_perCell', 'Median_Genes_perCell',
       'Median_UMI_perCell', 'Saturation', 'Live_percent', 'Total_Cells',
       'Live_Cells', 'method', 'exp_component_name', 'mapped_reads',
       'unmapped_reads', 'nonconf_mapped_reads', 'total.reads',
       'doublet.score'],
      dtype='object')

In [35]:
#file links is just the url links of where to download the difference 10Xv3 fastqs
tenX_flinks = pd.read_csv('/oak/stanford/groups/horence/rob/isoform_localizations/SRRS/pachter_annotations/BYVSTZP_2020/reference/10xv3/10xv3_file_links.txt')
tenX_flinks.head()

  http://data.nemoarchive.org/biccn/lab/zeng/transcriptome/scell/10X/raw/MOp_v3/L8TX_181211_01_A01_S01_L003.fastq.tar
0  http://data.nemoarchive.org/biccn/lab/zeng/tra...
1  http://data.nemoarchive.org/biccn/lab/zeng/tra...
2  http://data.nemoarchive.org/biccn/lab/zeng/tra...
3  http://data.nemoarchive.org/biccn/lab/zeng/tra...
4  http://data.nemoarchive.org/biccn/lab/zeng/tra...

In [36]:
#10X membership just has a mapping from cell-id to annotation
tenX_mem = pd.read_csv('/oak/stanford/groups/horence/rob/isoform_localizations/SRRS/pachter_annotations/BYVSTZP_2020/reference/10xv3/cluster.membership.csv')
tenX_mem.head()

                             Unnamed: 0   x
0  AAACCCAAGCTTCATG-1L8TX_181211_01_G12  42
1  AAACCCAAGTGAGGTC-1L8TX_181211_01_G12  41
2  AAACCCACACCAGCCA-1L8TX_181211_01_G12  42
3  AAACCCAGTGAACGGT-1L8TX_181211_01_G12  41
4  AAACCCAGTGGCATCC-1L8TX_181211_01_G12  20

# Is it possible to manually align some of the cluster_labels?

In [42]:
sorted(mop_meta['label'].unique())

['Astro_1',
 'Astro_2',
 'Astro_3',
 'Endo',
 'L23_IT_1',
 'L23_IT_2',
 'L23_IT_3',
 'L23_IT_4',
 'L23_IT_5',
 'L45_IT_1',
 'L45_IT_2',
 'L45_IT_3',
 'L45_IT_4',
 'L45_IT_5',
 'L45_IT_SSp_1',
 'L45_IT_SSp_2',
 'L56_NP_1',
 'L56_NP_2',
 'L5_ET_1',
 'L5_ET_2',
 'L5_ET_3',
 'L5_ET_4',
 'L5_ET_5',
 'L5_IT_1',
 'L5_IT_2',
 'L5_IT_3',
 'L5_IT_4',
 'L6_CT_1',
 'L6_CT_2',
 'L6_CT_3',
 'L6_CT_4',
 'L6_CT_5',
 'L6_CT_6',
 'L6_CT_7',
 'L6_CT_8',
 'L6_CT_9',
 'L6_IT_1',
 'L6_IT_2',
 'L6_IT_3',
 'L6_IT_Car3',
 'L6b_1',
 'L6b_2',
 'L6b_3',
 'Lamp5_1',
 'Lamp5_2',
 'Lamp5_3',
 'Lamp5_4',
 'Lamp5_5',
 'Lamp5_6',
 'Lamp5_7',
 'Lamp5_8',
 'Lamp5_9',
 'Micro_1',
 'Micro_2',
 'OPC',
 'Oligo_1',
 'Oligo_2',
 'Oligo_3',
 'PVM',
 'Peri',
 'Pvalb_1',
 'Pvalb_10',
 'Pvalb_11',
 'Pvalb_12',
 'Pvalb_2',
 'Pvalb_3',
 'Pvalb_4',
 'Pvalb_5',
 'Pvalb_6',
 'Pvalb_7',
 'Pvalb_8',
 'Pvalb_9',
 'SMC',
 'Sncg_1',
 'Sncg_2',
 'Sst_1',
 'Sst_2',
 'Sst_3',
 'Sst_4',
 'Sst_5',
 'Sst_6',
 'Sst_7',
 'Sst_8',
 'Sst_Chodl',
 'VLMC',
 'Vip_1',
 'Vip_10',
 'Vip_2',
 'Vip_3',
 'Vip_4',
 'Vip_5',
 'Vip_6',
 'Vip_7',
 'Vip_8',
 'Vip_9',
 'striatum_1',
 'striatum_2',
 'ventricle_1',
 'ventricle_2']

In [40]:
sorted(rzs_meta['cluster_label'].unique())

['Astro Aqp4',
 'Endo Slc38a5_1',
 'L2/3 IT',
 'L5 ET_1',
 'L5 ET_2',
 'L5 ET_3',
 'L5 IT Pld5',
 'L5 IT S100b',
 'L5 IT Tcap_1',
 'L5 IT Tcap_2',
 'L5 NP Slc17a8_1',
 'L5 NP Slc17a8_2',
 'L5 NP Slc17a8_3',
 'L6 CT Cpa6_1',
 'L6 CT Cpa6_2',
 'L6 CT Gpr139',
 'L6 CT Nxph2 Kit',
 'L6 CT Nxph2 Pou3f2_1',
 'L6 CT Nxph2 Pou3f2_2',
 'L6 IT Car3',
 'L6 IT Sulf1_1',
 'L6 IT Sulf1_2',
 'L6 IT Sulf1_3',
 'L6 IT Sulf1_4',
 'L6 NP Trh_1',
 'L6 NP Trh_2',
 'L6 NP Trh_3',
 'L6b Kcnip1',
 'L6b Ror1',
 'L6b Rprm',
 'L6b Shisa6',
 'Lamp5 Egln3_2_1',
 'Lamp5 Lhx6',
 'Lamp5 Pax6',
 'Lamp5 Pdlim5_1',
 'Lamp5 Pdlim5_2',
 'Lamp5 Slc35d3_1',
 'Macrophage',
 'OPC Pdgfra',
 'Oligo Enpp6_1',
 'Oligo Enpp6_2',
 'Oligo Opalin_1',
 'Oligo Opalin_2',
 'Pvalb Calb1',
 'Pvalb Gabrg1',
 'Pvalb Reln',
 'Pvalb Vipr2',
 'SMC',
 'Sncg_1',
 'Sncg_2',
 'Sst C1ql3_1',
 'Sst C1ql3_2',
 'Sst Calb2',
 'Sst Chodl',
 'Sst Crhr2_1',
 'Sst Crhr2_2',
 'Sst Hpse_2',
 'Sst Hpse_3',
 'Sst Hspe_1',
 'Sst Myh8_1',
 'Sst Myh8_2',
 'Sst Pvalb Etv1',
 'Sst Th',
 'VLMC Kcnj8',
 'Vip C1ql1',
 'Vip Cbln4_1',
 'Vip Cbln4_2',
 'Vip Chat',
 'Vip Col14a1',
 'Vip Crispld2',
 'Vip Gpc3',
 'Vip Htr1f_1',
 'Vip Htr1f_2',
 'Vip Igfbp6',
 'Vip Lypd1',
 'Vip Mybpc1_1',
 'Vip Mybpc1_2',
 'Vip Serpinf1']